### PR TITLE
#7 implement relative uri

### PR DESCRIPTION
**Pull request by TristanFAURE**
first attempt for relative uri. please tell me your remarks.

For instance i did not know how you want i deal with error manageent in RelativeResolverFactory

### CODE REVIEW

**Comment by TristanFAURE** [comment]
I have noted that your file encoding is not the same everywhere. Mostly utf-8 tests are ANSI

**Comment by StephPon** [comment]
For information, I have been able to validate this pull request on our Confluence serveur (5.8.18):

Given a remote Markdown file that embeds an image with a relative path (e.g. images/logo.png),
When the Markdown Macro is used in a Confluence page with the URL of the given Markdown file,
Then the Confluence page displays the image correctly in the web browser

Given a remote Markdown file that embeds a link with a relative path (e.g. features/feature1.md),
When the Markdown Macro is used a Confluence page with the URL of the remote Markdown file,
Then the Confluence page resolves the link correctly in the web browser

**Comment by borisdiakur** [comment]
Merci Tristan,
I’ve just reviewed and tested your PR briefly on my local machine. Well done! The only thing I noticed is that if you include a markdown file from https://raw.githubusercontent.com/, links in the resulting html document will always link to the raw markdown files instead of the rendered GitHub pages. I think this is ok though. On GitLab that should not be a problem at all since raw and rendered markdown is served from the same domain. Displaying images via relative urls works like a charm in any case. Thanks a lot!

**Comment by TristanFAURE** [comment]
Nice it fits your needs !

About the raw markdown aspects yes we noticed that and consider it was not a big deal. I'm not confluence API expert but maybe we should imagine as an improvement to reload the current page and "virtually" reference in the widget the new url. But not sure it is achievable or not.

Do you know when you will change the version and update the release in the atlassian marketplace ?

**Comment by borisdiakur** [comment]
> maybe we should imagine as an improvement to reload the current page and "virtually" reference in the widget the new url.

This would be kind of an iframe where the user has no possibility to click on the back-button. I would rather not do that. However one significant improvement could be to replace links to markdown files hosted on https://raw.githubusercontent.com/ with their according page on https://github.com/

> Do you know when you will change the version and update the release in the atlassian marketplace ?

I’ve released version 1.2.0 right after merging the PR 🚀

**Comment by TristanFAURE** [comment]
Do you have a preview of what you mean about raw.githubusercontent ?

If some mappings should be implemented it would be nice to have separate properties file with predefined mappings. 

But not sure it is possible with confluence plugins to upload jar and conf file ?

And .... thank you for the 1.2.0 !

**Pull request merged**
